global:
  scrape_interval:     1s
  evaluation_interval: 1s

remote_write:
  - url: "http://victoriametrics:8428/api/v1/write"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'victoriametrics'
    static_configs:
      - targets: ['victoriametrics:8428']